version: '3.7'

services:

  mongodb:
    image: mongo:4.4
    container_name: asd-project-backend-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: asd-project-backend-redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  onlineTicket:
    depends_on:
      - redis
      - mongodb
    restart: always
    image: ${IMAGE}:${TAG}
    container_name: asd-project-backend-app
    environment:
      DATABASE_NAME: ${MONGO_DB}
      DATABASE_USER: ${MONGO_INITDB_ROOT_USERNAME}
      DATABASE_PASS: ${MONGO_INITDB_ROOT_PASSWORD}
      DATABASE_HOST: ${MONGO_HOST}
      DATABASE_PORT: ${MONGO_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"