name: Test, Build, And Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  test:
   uses: ./.github/workflows/test.yml
  
  build:
   needs: test
   runs-on: ubuntu-20.04
   steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: PUSH IMAGE TO DOCKER-HUB
      run: |
        docker build -t "$IMAGE:latest" -f Dockerfile .
        echo "$REGISTRY_PASSWORD" | docker login --password-stdin -u $REGISTRY_USER
        docker push "$IMAGE:latest"
      env:
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        IMAGE: ${{ vars.IMAGE }}
  
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: PULL IMAGE AND RESTART
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 15m
          script: |
            cd /root/backend/
            echo -e "nameserver 78.157.42.101\nnameserver 78.157.42.100\noptions edns0 trust-ad\nsearch ." | sudo tee
            /etc/resolv.conf
            docker pull hosseinaghaei/asd-project-backend:latest
            echo "y" | docker-compose rm -s -v onlineTicket
            docker-compose up -d
