name: Test, Build, And Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  test:
   uses: ./.github/workflows/test.yml
  
  build:
   needs: test
   runs-on: ubuntu-20.04
   steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run the Build script
      run: |
        docker build -t "$IMAGE:latest" -f Dockerfile .
        echo "$REGISTRY_PASSWORD" | docker login --password-stdin -u $REGISTRY_USER
        docker push "$IMAGE:latest"
      env:
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        IMAGE: ${{ vars.IMAGE }}
  
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Remove old docker-compose and .env files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 5m
          script: |
            rm -f /root/backend/docker-compose.yml
      - name: Copy docker-compose file via ssh password
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 5m
          source: "docker-compose.yml"
          target: "/root/backend"
      - name: Run docker-compose up
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 15m
          script: |
            cd /root/backend/
            echo -e "nameserver 178.22.122.100\nnameserver 185.51.200.2\noptions edns0 trust-ad\nsearch ." | sudo tee /etc/resolv.conf
            docker-compose down
            docker-compose pull
            docker-compose up -d
