name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  test:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['4.4', '6.0']


    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: yarn
      working-directory: ./src
    - run: npm test
      working-directory: ./src
