name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: BUILD IMAGE
      run: |
        docker build -t "$IMAGE:latest" -f Dockerfile .
        docker-compose up -d
      env:
        IMAGE: ${{ vars.IMAGE }}

    - name: Run ESLint
      run: cd ./src && npx eslint --ext .js .
    - run: docker exec -it asd-project-backend-app sh && npm test